/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package hotel.view;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JRDesignQuery;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;


/**
 *
 * @author Nipun Lakshan
 */
public class AddSupplier extends javax.swing.JFrame {

    /**
     * Creates new form AddSupplier
     */
    private Connection con;
    
    public AddSupplier() {
        initComponents();
        
        try{
            
            Class.forName("com.mysql.jdbc.Driver");
            System.out.println("Driver Loaded");
            con = (com.mysql.jdbc.Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/java_hotel","root","");
            System.out.println("Connection Established");
        }
        
        catch (Exception ex){
            
            System.out.println(ex);
        }
        
        My_Connection db = My_Connection.getDatabaseConnection();
            con=db.getConnection();   
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButtonHome = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        SupplierParent = new javax.swing.JPanel();
        UDSupplier = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabelSUID1 = new javax.swing.JLabel();
        jTextFieldSUID = new javax.swing.JTextField();
        jLabelSUF = new javax.swing.JLabel();
        jTextFieldSUF = new javax.swing.JTextField();
        jLabelSUL = new javax.swing.JLabel();
        jTextFieldSUL = new javax.swing.JTextField();
        jLabelSUNIC = new javax.swing.JLabel();
        jTextFieldSUNIC = new javax.swing.JTextField();
        jLabelSUPhone = new javax.swing.JLabel();
        jTextFieldSUphone = new javax.swing.JTextField();
        jLabelSUMail = new javax.swing.JLabel();
        jTextFieldSUmail = new javax.swing.JTextField();
        jLabelSUCom = new javax.swing.JLabel();
        jTextFieldSUcom = new javax.swing.JTextField();
        jButtonSInsert1 = new javax.swing.JButton();
        jButtonSclear1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableupdate = new javax.swing.JTable();
        jButtonSUSe = new javax.swing.JButton();
        addbtn1 = new javax.swing.JButton();
        UDOrder = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabelOUID = new javax.swing.JLabel();
        jLabelOUsup = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jTextFieldOUSN = new javax.swing.JTextField();
        jTextFieldOUIC = new javax.swing.JTextField();
        jTextFieldOUIN = new javax.swing.JTextField();
        jTextFieldOUQ = new javax.swing.JTextField();
        jTextFieldOUUnit = new javax.swing.JTextField();
        jTextFieldOUTot = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jTextFieldOUODate = new javax.swing.JTextField();
        jButtonOUSearch = new javax.swing.JButton();
        jButtonOInsert1 = new javax.swing.JButton();
        ji1 = new javax.swing.JTextField();
        Report = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(153, 0, 51));
        jPanel1.setLayout(null);

        jButtonHome.setBackground(new java.awt.Color(153, 0, 51));
        jButtonHome.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButtonHome.setText("Main Menu");
        jButtonHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHomeActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonHome);
        jButtonHome.setBounds(10, 90, 180, 31);

        jButton2.setBackground(new java.awt.Color(153, 0, 51));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton2.setText("Supplier Handling");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(10, 170, 180, 34);

        jButton4.setBackground(new java.awt.Color(153, 0, 51));
        jButton4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton4.setText("Stock Order Handling");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4);
        jButton4.setBounds(10, 260, 180, 32);

        jButton5.setBackground(new java.awt.Color(153, 0, 51));
        jButton5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton5.setText("Report");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5);
        jButton5.setBounds(10, 330, 180, 30);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(10, 158, 200, 540);

        SupplierParent.setBackground(new java.awt.Color(153, 0, 51));
        SupplierParent.setLayout(new java.awt.CardLayout());

        UDSupplier.setBackground(new java.awt.Color(153, 0, 51));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Supplier Handling");

        jLabelSUID1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelSUID1.setText("Supplier ID");

        jTextFieldSUID.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        jLabelSUF.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelSUF.setText("First Name");

        jTextFieldSUF.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextFieldSUF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldSUFActionPerformed(evt);
            }
        });
        jTextFieldSUF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldSUFKeyPressed(evt);
            }
        });

        jLabelSUL.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelSUL.setText("Last Name");

        jLabelSUNIC.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelSUNIC.setText("NIC");
        jLabelSUNIC.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jTextFieldSUNIC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldSUNICActionPerformed(evt);
            }
        });

        jLabelSUPhone.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelSUPhone.setText("Contact Number");

        jLabelSUMail.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelSUMail.setText("E-mail");

        jLabelSUCom.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelSUCom.setText("Company Name");

        jButtonSInsert1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonSInsert1.setText("Update");
        jButtonSInsert1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSInsert1ActionPerformed(evt);
            }
        });

        jButtonSclear1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonSclear1.setText("Delete");
        jButtonSclear1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSclear1ActionPerformed(evt);
            }
        });

        jTableupdate.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "First Name", "Last Name", "NIC", "Phone No", "E-mail", "Company Name"
            }
        ));
        jScrollPane2.setViewportView(jTableupdate);

        jButtonSUSe.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonSUSe.setText("Search");
        jButtonSUSe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSUSeActionPerformed(evt);
            }
        });

        addbtn1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        addbtn1.setText("Insert");
        addbtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addbtn1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout UDSupplierLayout = new javax.swing.GroupLayout(UDSupplier);
        UDSupplier.setLayout(UDSupplierLayout);
        UDSupplierLayout.setHorizontalGroup(
            UDSupplierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UDSupplierLayout.createSequentialGroup()
                .addGroup(UDSupplierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(UDSupplierLayout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(UDSupplierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(UDSupplierLayout.createSequentialGroup()
                                .addGroup(UDSupplierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(UDSupplierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabelSUNIC)
                                        .addComponent(jLabelSUPhone)
                                        .addComponent(jLabelSUMail)
                                        .addComponent(jLabelSUCom))
                                    .addComponent(jLabelSUF, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelSUL, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelSUID1, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(4, 4, 4)
                                .addGroup(UDSupplierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextFieldSUcom)
                                    .addComponent(jTextFieldSUF)
                                    .addComponent(jTextFieldSUL)
                                    .addComponent(jTextFieldSUNIC)
                                    .addComponent(jTextFieldSUphone)
                                    .addComponent(jTextFieldSUmail)
                                    .addComponent(jTextFieldSUID, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(jButtonSUSe))
                            .addGroup(UDSupplierLayout.createSequentialGroup()
                                .addComponent(jButtonSInsert1)
                                .addGap(34, 34, 34)
                                .addComponent(jButtonSclear1)
                                .addGap(36, 36, 36)
                                .addComponent(addbtn1)))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 679, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(UDSupplierLayout.createSequentialGroup()
                        .addGap(184, 184, 184)
                        .addComponent(jLabel9)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        UDSupplierLayout.setVerticalGroup(
            UDSupplierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UDSupplierLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addGroup(UDSupplierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(UDSupplierLayout.createSequentialGroup()
                        .addGroup(UDSupplierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelSUID1)
                            .addComponent(jTextFieldSUID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonSUSe))
                        .addGap(18, 18, 18)
                        .addGroup(UDSupplierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelSUF)
                            .addComponent(jTextFieldSUF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(UDSupplierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelSUL)
                            .addComponent(jTextFieldSUL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addGroup(UDSupplierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelSUNIC)
                            .addComponent(jTextFieldSUNIC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(UDSupplierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelSUPhone)
                            .addComponent(jTextFieldSUphone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(UDSupplierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelSUMail)
                            .addComponent(jTextFieldSUmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(UDSupplierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelSUCom)
                            .addComponent(jTextFieldSUcom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addGroup(UDSupplierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonSInsert1)
                            .addComponent(jButtonSclear1)
                            .addComponent(addbtn1)))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(203, 203, 203))
        );

        SupplierParent.add(UDSupplier, "card3");

        UDOrder.setBackground(new java.awt.Color(153, 0, 51));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setText("Stock Order Handling");

        jLabelOUID.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelOUID.setText("Supplier ID");

        jLabelOUsup.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelOUsup.setText("Supplier Name");

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel16.setText("Order Date");
        jLabel16.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel17.setText("Item Code");

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel18.setText("Item Name");

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel19.setText("Quantity");

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel20.setText("Unit Price");

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel21.setText("Total");

        jTextFieldOUUnit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldOUUnitActionPerformed(evt);
            }
        });

        jTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Supplier ID", "Supplier Name", "Order Date", "Item Code", "Item Name", "Quantity", "Unit Price", "Total"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Float.class, java.lang.Float.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane4.setViewportView(jTable4);

        jButton9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton9.setText("Update");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jButton10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton10.setText("Delete");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jButtonOUSearch.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButtonOUSearch.setText("Search");
        jButtonOUSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOUSearchActionPerformed(evt);
            }
        });

        jButtonOInsert1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonOInsert1.setText("Insert");
        jButtonOInsert1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOInsert1ActionPerformed(evt);
            }
        });

        ji1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ji1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout UDOrderLayout = new javax.swing.GroupLayout(UDOrder);
        UDOrder.setLayout(UDOrderLayout);
        UDOrderLayout.setHorizontalGroup(
            UDOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UDOrderLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(UDOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(UDOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabelOUID)
                        .addComponent(jLabel16)
                        .addComponent(jLabel17)
                        .addComponent(jLabel18)
                        .addComponent(jLabel19)
                        .addComponent(jLabel20)
                        .addComponent(jLabel21)
                        .addComponent(jLabelOUsup))
                    .addGroup(UDOrderLayout.createSequentialGroup()
                        .addComponent(jButton9)
                        .addGap(27, 27, 27)))
                .addGroup(UDOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(UDOrderLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jButton10)
                        .addGap(50, 50, 50)
                        .addComponent(jButtonOInsert1))
                    .addGroup(UDOrderLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(UDOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel13)
                            .addComponent(jTextFieldOUSN, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
                            .addComponent(jTextFieldOUIC, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldOUIN, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldOUQ, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldOUUnit, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldOUTot, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldOUODate, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
                            .addComponent(ji1, javax.swing.GroupLayout.Alignment.LEADING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonOUSearch)))
                .addGap(32, 32, Short.MAX_VALUE)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 694, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        UDOrderLayout.setVerticalGroup(
            UDOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UDOrderLayout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(UDOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(UDOrderLayout.createSequentialGroup()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(UDOrderLayout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addGap(46, 46, 46)
                        .addGroup(UDOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(UDOrderLayout.createSequentialGroup()
                                .addGroup(UDOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabelOUID)
                                    .addComponent(jButtonOUSearch)
                                    .addComponent(ji1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(UDOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabelOUsup)
                                    .addComponent(jTextFieldOUSN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(UDOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel16)
                                    .addComponent(jTextFieldOUODate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(UDOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel17)
                                    .addComponent(jTextFieldOUIC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(UDOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel18)
                                    .addComponent(jTextFieldOUIN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(UDOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel19)
                                    .addComponent(jTextFieldOUQ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(UDOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel20)
                                    .addComponent(jTextFieldOUUnit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(jTextFieldOUTot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(5, 5, 5))
                            .addComponent(jLabel21))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                        .addGroup(UDOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton9)
                            .addComponent(jButton10)
                            .addComponent(jButtonOInsert1))
                        .addGap(66, 66, 66))))
        );

        SupplierParent.add(UDOrder, "card5");

        javax.swing.GroupLayout ReportLayout = new javax.swing.GroupLayout(Report);
        Report.setLayout(ReportLayout);
        ReportLayout.setHorizontalGroup(
            ReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1140, Short.MAX_VALUE)
        );
        ReportLayout.setVerticalGroup(
            ReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 540, Short.MAX_VALUE)
        );

        SupplierParent.add(Report, "card6");

        getContentPane().add(SupplierParent);
        SupplierParent.setBounds(220, 160, 1140, 540);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hotel/view/Untitled-1.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 10, 1330, 140);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        SupplierParent.removeAll();
        SupplierParent.add(UDSupplier);
        SupplierParent.repaint();
        SupplierParent.revalidate();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButtonHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHomeActionPerformed
        // TODO add your handling code here:   
    }//GEN-LAST:event_jButtonHomeActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        SupplierParent.removeAll();
        SupplierParent.add(UDOrder);
        SupplierParent.repaint();
        SupplierParent.revalidate();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        
        try{
         JasperDesign jasdi =JRXmlLoader.load("C:\\Users\\Nipun Lakshan\\Documents\\NetBeansProjects\\Hotel Managemet\\src\\hotel\\view\\report7.jrxml");
        String sql="SELECT `Suplpier_ID`, `first_name`, `last_name`, `NIC`, `contact_no`, `mail`, `company_name` FROM `supplier`";
        JRDesignQuery newQuary=new JRDesignQuery();
      
      
        newQuary.setText(sql);
        jasdi.setQuery(newQuary);
      
      
        JasperReport js =JasperCompileManager.compileReport(jasdi);
     
        JasperPrint jp = JasperFillManager.fillReport(js,null,con);
      
        JasperViewer.viewReport(jp);
        }
        catch(Exception ex){
            JOptionPane.showMessageDialog(this,ex);
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jTextFieldSUFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldSUFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldSUFActionPerformed

    private void jTextFieldSUNICActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldSUNICActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldSUNICActionPerformed

    private void jButtonSInsert1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSInsert1ActionPerformed
        // TODO add your handling code here:
        
         int Suplpie_ID = Integer.parseInt(jTextFieldSUID.getText());
            
            String firstname = jTextFieldSUF.getText();
            String lastname = jTextFieldSUL.getText();
            String nic = jTextFieldSUNIC.getText();
            String Contactno = jTextFieldSUphone.getText();
            String Mail = jTextFieldSUmail.getText();
            String CompanyN = jTextFieldSUcom.getText();
            
           // String priceItem = qHandae.getText();
            
            
            try{
                
                //Edit the fire alarm sensor details in the database
                
                Statement s = con.createStatement();
                s.execute("update supplier set first_name='"+firstname+"',last_name='"+lastname+"',NIC='"+nic+"',contact_no='"+Contactno+"',mail='"+Mail+"',company_name='"+CompanyN+"' where Suplpier_ID="+Suplpie_ID);
                JOptionPane.showMessageDialog(this, "Records Are Updated!");
                
                setjTableupdate();
                //s.close();
                resetData();
                    
                
            }
            catch(Exception ex){
                
                JOptionPane.showMessageDialog(this,ex.getMessage()); // "Can't Update Records!");
                
            }
        
    }//GEN-LAST:event_jButtonSInsert1ActionPerformed

    private void jButtonSUSeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSUSeActionPerformed
        // TODO add your handling code here:
         Functionlec f1 = new Functionlec();
        
        ResultSet rs = null;
        
        String firstname = "first_name";
        String lastname = "last_name";
        String nic = "NIC";
        String Contactno = "contact_no";
        String Mail = "mail";
        String CompanyN = "company_name";
       
        
        rs = f1.find(jTextFieldSUID.getText());
        
        try{
            
            if(rs.next()){
                
                jTextFieldSUF.setText(rs.getString("first_name"));
                jTextFieldSUL.setText(rs.getString("last_name"));
                jTextFieldSUNIC.setText(rs.getString("NIC"));
                jTextFieldSUphone.setText(rs.getString("contact_no"));
                jTextFieldSUmail.setText(rs.getString("mail"));
                jTextFieldSUcom.setText(rs.getString("company_name"));
                
               
            }else{
                JOptionPane.showMessageDialog(null, "No Data Show");
            }
            
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
        
    
    }//GEN-LAST:event_jButtonSUSeActionPerformed

    private void jButtonSclear1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSclear1ActionPerformed
        // TODO add your handling code here:
         try{
                               
                int supid = Integer.parseInt(jTextFieldSUID.getText());
                
                Statement s = con.createStatement();
                s.execute("delete from supplier where Suplpier_ID ="+supid);
                JOptionPane.showMessageDialog(this, "Record Are Deleted!");
                
            
            }
            catch(Exception ex){
                
                JOptionPane.showMessageDialog(this, "Can't Delete Records!");
            }
    }//GEN-LAST:event_jButtonSclear1ActionPerformed

    private void jButtonOUSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOUSearchActionPerformed
        // TODO add your handling code here:
        Functionlec3 f1 = new Functionlec3();
        
        ResultSet rs = null;
        
        String SupID = "Supplier_ID";
        String Supname = "Supplier_name";
        String OrderD = "Order_date";
        String Itemc = "Item_code";
        String Itemname = "Item_name";
        String Quan = "Quantity";
        String Unitp = "Unit_price";
        String Tot = "Total";
       
        
        rs = f1.find(ji1.getText());
        
        try{
            
            if(rs.next()){
                
              //  jTextFieldOUSID1.setText(rs.getString("Supplier_ID"));
                jTextFieldOUSN.setText(rs.getString("Supplier_name"));
                jTextFieldOUODate.setText(rs.getString("Order_date"));
                jTextFieldOUIC.setText(rs.getString("Item_code"));
                jTextFieldOUIN.setText(rs.getString("Item_name"));
                jTextFieldOUQ.setText(rs.getString("Quantity"));
                jTextFieldOUUnit.setText(rs.getString("Unit_price"));
                jTextFieldOUTot.setText(rs.getString("Total"));
                
                
               
            }else{
                JOptionPane.showMessageDialog(null, "No Data Show");
            }
            
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
                                                   
    }//GEN-LAST:event_jButtonOUSearchActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        int Supplier_ID  = Integer.parseInt(ji1.getText());
            
         //   String SupplierID = jTextFieldOUSID1.getText();
            String SupplierN = jTextFieldOUSN.getText();
            String OrderD = jTextFieldOUODate.getText();
            String ItemC = jTextFieldOUIC.getText();
            String ItemN = jTextFieldOUIN.getText();
            String Qun = jTextFieldOUQ.getText();
            String Unitp = jTextFieldOUUnit.getText();
            String Tot = jTextFieldOUTot.getText();
            
            
           // String priceItem = qHandae.getText();
            
            
            try{
                
                //Edit the fire alarm sensor details in the database
                
                Statement s = con.createStatement();
                s.execute("update order1 set Supplier_name='"+SupplierN+"',Order_date='"+OrderD+"',Item_code='"+ItemC+"',Item_name='"+ItemN+"',Quantity='"+Qun+"',Unit_price='"+Unitp+"',Total='"+ Tot+"' where Supplier_ID ="+Supplier_ID);
                JOptionPane.showMessageDialog(this, "Records Are Updated!");
                
                
                setjTable4();
                //s.close();
                resetData();
                    
                
            }
            catch(Exception ex){
                
                JOptionPane.showMessageDialog(this,ex.getMessage()); // "Can't Update Records!");
                
            }
        
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jTextFieldSUFKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldSUFKeyPressed
        // TODO add your handling code here:
        char c = evt.getKeyChar();
         if(Character.isDigit(c)){
             JOptionPane.showMessageDialog(null,"Inavlid Input,Please Enter Characters");
         }
    }//GEN-LAST:event_jTextFieldSUFKeyPressed

    private void addbtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addbtn1ActionPerformed
        // TODO add your handling code here:
       // String fname = jTextFieldSF.getText();
       // String lname = jTextFieldSL.getText();
       // String nic = jTextFieldSNIC.getText();
       // String conph = jTextFieldSphone.getText();
       // String mail = jTextFieldSmail.getText();
       // String comname = jTextFieldScom.getText();
        
            String firstname = jTextFieldSUF.getText();
            String lastname = jTextFieldSUL.getText();
            String nic = jTextFieldSUNIC.getText();
            String Contactno = jTextFieldSUphone.getText();
            String Mail = jTextFieldSUmail.getText();
            String CompanyN = jTextFieldSUcom.getText();
        
        try{
            
            Statement s = con.createStatement();    
            s.execute("INSERT INTO supplier(first_name,last_name,NIC,contact_no,mail,company_name)values('"+firstname+"','"+lastname+"','"+nic+"','"+Contactno+"','"+Mail+"','"+CompanyN+"')"); 
            
     
             JOptionPane.showMessageDialog(this, "Record Are Add");
             
                setjTableupdate();
                //s.close();
                resetData();
             
        }catch(Exception ex){
            
            JOptionPane.showMessageDialog(this, ex);
        }
    }//GEN-LAST:event_addbtn1ActionPerformed

    private void jButtonOInsert1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOInsert1ActionPerformed
        // TODO add your handling code here:
        
            //  String SupplierID = jTextFieldOUSID.getText();
            String SupplierN = jTextFieldOUSN.getText();
            String OrderD = jTextFieldOUODate.getText();
            String ItemC = jTextFieldOUIC.getText();
            String ItemN = jTextFieldOUIN.getText();
            String Qun = jTextFieldOUQ.getText();
            String Unitp = jTextFieldOUUnit.getText();
            String Tot = jTextFieldOUTot.getText();
        
        try{
            
            Statement s = con.createStatement();    
            s.execute("INSERT INTO order1(Supplier_name,Order_date,Item_code,Item_name,Quantity,Unit_price,Total)values ('"+SupplierN+"','"+OrderD+"','"+ItemC+"','"+ItemN+"','"+Qun+"','"+Unitp+"','"+Tot+"')"); 
     
             JOptionPane.showMessageDialog(this, "Record Are Add");
             
                setjTable4();
                //s.close();
                resetData();    
             
        }catch(Exception ex){
            
            JOptionPane.showMessageDialog(this, ex);
        }
    }//GEN-LAST:event_jButtonOInsert1ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
          try{
                               
                int supid = Integer.parseInt(ji1.getText());
                
                Statement s = con.createStatement();
                s.execute("delete from order1 where Supplier_ID  ="+supid);
                JOptionPane.showMessageDialog(this, "Record Are Deleted!");
                
            
            }
            catch(Exception ex){
                
                JOptionPane.showMessageDialog(this, "Can't Delete Records!");
            }
        
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jTextFieldOUUnitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldOUUnitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldOUUnitActionPerformed

    private void ji1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ji1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ji1ActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddSupplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddSupplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddSupplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddSupplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddSupplier().setVisible(true);
            }
        });
    }

public class Functionlec{
        
        Connection con = null;
        ResultSet rs = null;
        PreparedStatement ps =null;
        
        public ResultSet find(String s){
            
            try{
                
                con = DriverManager.getConnection("jdbc:mysql://localhost:3306/java_hotel", "root", "");
                ps = con.prepareStatement("select * from supplier where Suplpier_ID=?");
                ps.setString(1,s);
                rs = ps.executeQuery();
                
            }catch(Exception ex){
                JOptionPane.showMessageDialog(null, ex.getMessage());
            }
            
            return rs;
            
        }
       
    }

public class Functionlec3{
    
    Connection con = null;
    ResultSet rs = null;
    PreparedStatement ps =null;
    
     public ResultSet find(String s){
         try{
                
                con = DriverManager.getConnection("jdbc:mysql://localhost:3306/java_hotel", "root", "");
                ps = con.prepareStatement("select * from order1 where Supplier_ID=?");
                ps.setString(1,s);
                rs = ps.executeQuery();
                
            }catch(Exception ex){
                JOptionPane.showMessageDialog(null, ex.getMessage());
            }
            
            return rs;
            
        }
    
}

 
 
 private void resetData() {

  
        
    }
 
 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Report;
    private javax.swing.JPanel SupplierParent;
    private javax.swing.JPanel UDOrder;
    private javax.swing.JPanel UDSupplier;
    private javax.swing.JButton addbtn1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton9;
    private javax.swing.JButton jButtonHome;
    private javax.swing.JButton jButtonOInsert1;
    private javax.swing.JButton jButtonOUSearch;
    private javax.swing.JButton jButtonSInsert1;
    private javax.swing.JButton jButtonSUSe;
    private javax.swing.JButton jButtonSclear1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelOUID;
    private javax.swing.JLabel jLabelOUsup;
    private javax.swing.JLabel jLabelSUCom;
    private javax.swing.JLabel jLabelSUF;
    private javax.swing.JLabel jLabelSUID1;
    private javax.swing.JLabel jLabelSUL;
    private javax.swing.JLabel jLabelSUMail;
    private javax.swing.JLabel jLabelSUNIC;
    private javax.swing.JLabel jLabelSUPhone;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable4;
    private javax.swing.JTable jTableupdate;
    private javax.swing.JTextField jTextFieldOUIC;
    private javax.swing.JTextField jTextFieldOUIN;
    private javax.swing.JTextField jTextFieldOUODate;
    private javax.swing.JTextField jTextFieldOUQ;
    private javax.swing.JTextField jTextFieldOUSN;
    private javax.swing.JTextField jTextFieldOUTot;
    private javax.swing.JTextField jTextFieldOUUnit;
    private javax.swing.JTextField jTextFieldSUF;
    private javax.swing.JTextField jTextFieldSUID;
    private javax.swing.JTextField jTextFieldSUL;
    private javax.swing.JTextField jTextFieldSUNIC;
    private javax.swing.JTextField jTextFieldSUcom;
    private javax.swing.JTextField jTextFieldSUmail;
    private javax.swing.JTextField jTextFieldSUphone;
    private javax.swing.JTextField ji1;
    // End of variables declaration//GEN-END:variables


private void setjTableupdate() {

        try {

            int rows = 0;
            int rowIndex = 0;

            Statement s = con.createStatement();
            ResultSet rs = s.executeQuery("select * from supplier order by Suplpier_ID desc");

            if (rs.next()) {

                rs.last();
                rows = rs.getRow();
                rs.beforeFirst();
            }

            String[][] data = new String[rows][7];

            while (rs.next()) {

                data[rowIndex][0] = rs.getInt(1) + "";
                data[rowIndex][1] = rs.getString(2);
                data[rowIndex][2] = rs.getString(3);
                data[rowIndex][3] = rs.getString(4);
                data[rowIndex][4] = rs.getString(5);
                data[rowIndex][5] = rs.getString(6);
                data[rowIndex][6] = rs.getString(7);
               
               

                rowIndex++;

            }

                String[] cols = {"SuplpiID","first_name","last_name","NIC","contact_no","mail","company_name"};
                DefaultTableModel model = new DefaultTableModel(data, cols);
                jTableupdate.setModel(model);


                rs.close();
            s.close();

        } catch (Exception ex) {

            JOptionPane.showMessageDialog(this, "Can't Retrieve Data!");

        }

    }

    private void setjTable4() {

        try {

            int rows = 0;
            int rowIndex = 0;

            Statement s = con.createStatement();
            ResultSet rs = s.executeQuery("select * from order1 order by Supplier_ID  desc");

            if (rs.next()) {

                rs.last();
                rows = rs.getRow();
                rs.beforeFirst();
            }

            String[][] data = new String[rows][8];

            while (rs.next()) {

                data[rowIndex][0] = rs.getInt(1) + "";
                data[rowIndex][1] = rs.getString(2);
                data[rowIndex][2] = rs.getString(3);
                data[rowIndex][3] = rs.getString(4);
                data[rowIndex][4] = rs.getString(5);
                data[rowIndex][5] = rs.getString(6);
                data[rowIndex][6] = rs.getString(7);
                 data[rowIndex][7] = rs.getString(8);
               
               

                rowIndex++;

            }

            String[] cols = {"SuplpiID","first_name","last_name","NIC","contact_no","mail","company_name","d"};
            DefaultTableModel model = new DefaultTableModel(data, cols);
            jTable4.setModel(model);

            
            rs.close();
            s.close();

        } catch (Exception ex) {

            JOptionPane.showMessageDialog(this, "Can't Retrieve Data!");

        }

    }
 }
